TARGET		= list.test 

INCPATH		= ../include
LIBPATH		= ../lib

CXX		?= g++
CXXFLAGS	?= -g3 -O3 -W -Wall
LDFLAGS		?= -lulib -lrt -lm
DEBUG		?=

%.test: test_%.c
	gcc -I $(INCPATH) $(CXXFLAGS) $(DEBUG) $< -o $@ -L $(LIBPATH) $(LDFLAGS)

.PHONY: all clean

all: $(TARGET)

clean:
	rm -rf $(TARGET)
